---
name: perl-lsp
description: Perl language server built on tree-sitter-perl
homepage: https://github.com/tree-sitter-perl/perl-tree-sitter-lsp
licenses:
  - Artistic-2.0
languages:
  - Perl
categories:
  - LSP

source:
  id: pkg:github/tree-sitter-perl/perl-tree-sitter-lsp@{{ version }}
  asset:
    - target: linux_x64
      file: perl-lsp-x86_64-unknown-linux-gnu.tar.gz
      bin: perl-lsp
    - target: darwin_x64
      file: perl-lsp-x86_64-apple-darwin.tar.gz
      bin: perl-lsp
    - target: darwin_arm64
      file: perl-lsp-aarch64-apple-darwin.tar.gz
      bin: perl-lsp
    - target: win_x64
      file: perl-lsp-x86_64-pc-windows-msvc.zip
      bin: perl-lsp.exe

bin:
  perl-lsp: "{{source.asset.bin}}"

neovim:
  lspconfig: perl_lsp
